// This file is auto-generated by @hey-api/openapi-ts

export type * from './types.gen';
export * from './sdk.gen';

// Export backward-compatible services
export { UsersService, ProductsService } from './services';

// Export client for configuration
export { client } from './client.gen';

// Re-export types for convenience
export type { User, Product } from './types.gen';

// Export a simple OpenAPI config object for backward compatibility
export const OpenAPI = {
  BASE: '',
  VERSION: '1.0',
  WITH_CREDENTIALS: false,
  CREDENTIALS: 'include' as const,
  TOKEN: undefined as string | undefined,
  USERNAME: undefined as string | undefined,
  PASSWORD: undefined as string | undefined,
  HEADERS: undefined as Record<string, string> | undefined,
  ENCODE_PATH: undefined as ((path: string) => string) | undefined,
};
