// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteApiProductsByIdData, DeleteApiProductsByIdResponses, DeleteApiUsersByIdData, DeleteApiUsersByIdResponses, GetApiProductsByIdData, GetApiProductsByIdResponses, GetApiProductsData, GetApiProductsResponses, GetApiUsersByIdData, GetApiUsersByIdResponses, GetApiUsersData, GetApiUsersResponses, PostApiProductsData, PostApiProductsResponses, PostApiUsersData, PostApiUsersResponses, PutApiProductsByIdData, PutApiProductsByIdResponses, PutApiUsersByIdData, PutApiUsersByIdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export const getApiProducts = <ThrowOnError extends boolean = false>(options?: Options<GetApiProductsData, ThrowOnError>) => (options?.client ?? client).get<GetApiProductsResponses, unknown, ThrowOnError>({ url: '/api/Products', ...options });

export const postApiProducts = <ThrowOnError extends boolean = false>(options?: Options<PostApiProductsData, ThrowOnError>) => (options?.client ?? client).post<PostApiProductsResponses, unknown, ThrowOnError>({
    url: '/api/Products',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiProductsById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiProductsByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiProductsByIdResponses, unknown, ThrowOnError>({ url: '/api/Products/{id}', ...options });

export const getApiProductsById = <ThrowOnError extends boolean = false>(options: Options<GetApiProductsByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiProductsByIdResponses, unknown, ThrowOnError>({ url: '/api/Products/{id}', ...options });

export const putApiProductsById = <ThrowOnError extends boolean = false>(options: Options<PutApiProductsByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiProductsByIdResponses, unknown, ThrowOnError>({
    url: '/api/Products/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

export const getApiUsers = <ThrowOnError extends boolean = false>(options?: Options<GetApiUsersData, ThrowOnError>) => (options?.client ?? client).get<GetApiUsersResponses, unknown, ThrowOnError>({ url: '/api/Users', ...options });

export const postApiUsers = <ThrowOnError extends boolean = false>(options?: Options<PostApiUsersData, ThrowOnError>) => (options?.client ?? client).post<PostApiUsersResponses, unknown, ThrowOnError>({
    url: '/api/Users',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

export const deleteApiUsersById = <ThrowOnError extends boolean = false>(options: Options<DeleteApiUsersByIdData, ThrowOnError>) => (options.client ?? client).delete<DeleteApiUsersByIdResponses, unknown, ThrowOnError>({ url: '/api/Users/{id}', ...options });

export const getApiUsersById = <ThrowOnError extends boolean = false>(options: Options<GetApiUsersByIdData, ThrowOnError>) => (options.client ?? client).get<GetApiUsersByIdResponses, unknown, ThrowOnError>({ url: '/api/Users/{id}', ...options });

export const putApiUsersById = <ThrowOnError extends boolean = false>(options: Options<PutApiUsersByIdData, ThrowOnError>) => (options.client ?? client).put<PutApiUsersByIdResponses, unknown, ThrowOnError>({
    url: '/api/Users/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
